name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        GALILEO_USERNAME: ${{ secrets.GALILEO_USERNAME }}
        GALILEO_PASSWORD: ${{ secrets.GALILEO_PASSWORD }}
      run: |
        echo $GALILEO_USERNAME >> secrets.txt
        echo $GALILEO_PASSWORD >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
