name: test

on:
  push:
    branches:
      - fix/notebooks-run-as-is # TODO: change to main before merge
  pull_request:
    types: [opened, synchronize]

env:
  MINIMIZE_FOR_CI: "true"
  GALILEO_USERNAME: ${{ secrets.GALILEO_USERNAME }}
  GALILEO_PASSWORD: ${{ secrets.GALILEO_PASSWORD }}

jobs:
  mltc-pytorch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --debug --to notebook --execute examples/multi_label_text_classification/pytorch.ipynb

  mltc-tensorflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/multi_label_text_classification/tensorflow.ipynb

  ner-pytorch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/named_entity_recognition/pytorch.ipynb

  ner-spacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/named_entity_recognition/spacy.ipynb

  ner-tensorflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/named_entity_recognition/tensorflow.ipynb

  nli-pytorch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/pytorch.ipynb

  nli-tensorflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/natural_language_inference/tensorflow.ipynb

  tc-keras:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/text_classification/keras.ipynb

  tc-pytorch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/text_classification/pytorch.ipynb

  tc-tensorflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: install dependencies
        run: pip install -r requirements-ci.txt

      - name: run notebook
        run: jupyter nbconvert --to notebook --execute examples/text_classification/tensorflow.ipynb
